name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${APPDATA}/immich/upload:/data
    depends_on:
      - redis
      - database
    restart: always
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/immich.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.home.phuchoang.sbs`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities:
                - gpu
                - compute
                - video

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    volumes:
      - ${APPDATA}/immich/model-cache:/cache
    restart: always
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/immich.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    restart: always
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/immich.env

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3
    environment:
      TZ: ${TZ}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: HDD
    volumes:
      - ${APPDATA}/immich/database:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/immich.env

networks:
  proxy:
    external: true
