name: vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:testing
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/vaultwarden.env
    environment:
      TZ: ${TZ}
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: autofill-overlay,autofill-v2,browser-fileless-import,fido2-vault-credentials
      IP_HEADER: X-Forwarded-For
      PUSH_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      WEB_VAULT_ENABLED: "true"
    volumes:
      - ${APPDATA}/vaultwarden/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.vps.phuchoang.sbs`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
