name: suwayomi

services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:preview
    container_name: suwayomi
    hostname: suwayomi
    restart: always
    environment:
      TZ: ${TZ}
      EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
      FLARESOLVERR_ENABLED: "true"
      FLARESOLVERR_URL: http://flaresolverr:8191
    networks:
      - proxy
    volumes:
      - ${MEDIA}/manga:/home/suwayomi/data
      - ${APPDATA}/suwayomi/data:/home/suwayomi/.local/share/Tachidesk
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.suwayomi.rule=Host(`suwayomi.home.phuchoang.sbs`)"
      - "traefik.http.routers.suwayomi.entrypoints=websecure"
      - "traefik.http.routers.suwayomi.tls=true"
      - "traefik.http.routers.suwayomi.tls.certresolver=letsencrypt"
      - "traefik.http.services.suwayomi.loadbalancer.server.port=4567"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - proxy

  koharu:
    image: ghcr.io/phuchoang2603/koharu:latest
    container_name: koharu
    hostname: koharu
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    volumes:
      - ${APPDATA}/suwayomi/koharu:/home/koharu/.local/share/Koharu
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koharu.rule=Host(`koharu.home.phuchoang.sbs`)"
      - "traefik.http.routers.koharu.entrypoints=websecure"
      - "traefik.http.routers.koharu.tls=true"
      - "traefik.http.routers.koharu.tls.certresolver=letsencrypt"
      - "traefik.http.services.koharu.loadbalancer.server.port=4000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

  manga-watch:
    image: ghcr.io/phuchoang2603/koharu-watch-manga:latest
    container_name: manga-watch
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      KOHARU_SERVER_URL: http://koharu:4000
      INPUT_ROOT: /data/downloads/mangas
      OUTPUT_ROOT: /data/translated
      LLM_TARGET_JSON: '{"kind":"provider","providerId":"openai-compatible","modelId":"gpt-5-nano"}'
    volumes:
      - ${MEDIA}/manga:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
