require("mini.icons").setup()
MiniIcons.mock_nvim_web_devicons()

require("plugins.snacks")
require("plugins.whichkey")
require("plugins.blink")
require("plugins.yazi")
require("plugins.treesitter")
require("plugins.conform")
require("plugins.git")
require("plugins.quicker")
require("plugins.sidekick")
require("plugins.neotest-dap")
