services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.31.0
    restart: unless-stopped
    volumes:
      - ${APPDATA}/hoarderr/data:/data
    networks:
      - proxy
    environment:
      TZ: ${TZ}
      PUID: "1000"
      PGID: "1000"
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    env_file:
      - ${SECRETS_DIR}/karakeep.env
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.rule=Host(`karakeep.home.phuchoang.sbs`)"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.tls=true"
      - "traefik.http.routers.karakeep.tls.certresolver=letsencrypt"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    networks:
      - proxy
    environment:
      TZ: ${TZ}
    env_file:
      - ${SECRETS_DIR}/karakeep.env
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    volumes:
      - ${APPDATA}/hoarderr/meilisearch:/meili_data
    networks:
      - proxy
    env_file:
      - ${SECRETS_DIR}/karakeep.env
    environment:
      TZ: ${TZ}
      PUID: "1000"
      PGID: "1000"
      MEILI_NO_ANALYTICS: "true"

networks:
  proxy:
    external: true
